/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Person p = new Person();
        p.setName("Pessoa");
        p.setCpf("123.123.123-23");
        p.setEmail("a@a.com");

        System.out.println(p);

    };
}
