/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import ads.poo.produtos.Dimensao;
import ads.poo.produtos.SemFio;
import ads.poo.produtos.Telefone;

public class App {

    public static void main(String[] args) {
        Telefone telefone = new Telefone(1, "123", "samsung", 300, new Dimensao(10,10,10));
        Telefone telefoneSemFio = new SemFio(1, "123", "samsung", 200, new Dimensao(30,5,10), 2.4, 200, 1000);
        SemFio a = (SemFio) telefoneSemFio;
        System.out.println(telefone.imprimirDados());
        System.out.println(telefoneSemFio.imprimirDados());
    }
}
