/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Horario hora1 = new Horario(121, 10, 0);
        System.out.println(hora1);
    }
}
