/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.util.ArrayList;

public class Agenda {
    private ArrayList<Contato> contatos;

    public Agenda(ArrayList<Contato> contatos) {
        this.contatos = contatos;
    }

    public boolean addContato(Contato contato) {
        return this.contatos.add(contato);
    }

    public boolean removeContato(int index) {
        this.contatos.remove(index);
        return true;
    }

    public boolean addTelefone(int index, String rotulo, String valor) {
        return this.contatos.get(index).AddTelefone(rotulo, valor);
    }

    public boolean addEmail(int index, String rotulo, String valor) {
        return this.contatos.get(index).AddEmail(rotulo, valor);
    }

    public boolean updateTelefone(int index, int telIndex, String rotulo, String valor) {
        return this.contatos.get(index).updateTelefone(telIndex, rotulo, valor);
    }

    public boolean updateEmail(int index, int emailIndex, String rotulo, String valor) {
        return this.contatos.get(index).updateEmail(emailIndex, rotulo, valor);
    }

    public boolean removeTelefone(int index, int telIndex) {
        return this.contatos.get(index).removeTelefone(telIndex);
    }

    public boolean removeEmail(int index, int emailIndex) {
        return this.contatos.get(index).removeEmail(emailIndex);
    }

    public String toString() {
        StringBuilder sb = new StringBuilder();

        sb.append("(");
        for(int i = 0; i < this.contatos.size(); i++){
            sb.append(i);
            sb.append(" - ");
            sb.append("(");
            sb.append(this.contatos.get(i));
            sb.append(")");
            if(i != this.contatos.size() -1){
                sb.append(", ");
            }
        }
        sb.append(")");

        return sb.toString();
    }

}
