/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

public class Contato {
    private String nome;
    private String sobrenome;
    private LocalDate dataNasc;
    private ArrayList<Telefone> telefones;
    private ArrayList<Email> emails;

    public Contato(String nome, String sobrenome, LocalDate dataNasc, ArrayList<Telefone> telefones, ArrayList<Email> emails){
        this.nome = nome;
        this.sobrenome = sobrenome;
        this.dataNasc = dataNasc;
        this.telefones = telefones;
        this.emails = emails;
    }

    public boolean AddTelefone(String rotulo, String valor){
        return this.telefones.add(new Telefone(rotulo, valor));
    }

    public boolean AddEmail(String rotulo, String valor){
        return this.emails.add(new Email(rotulo, valor));
    }

    public boolean removeTelefone(int index){
        this.telefones.remove(index);
        return true;
    }

    public boolean removeEmail(int index){
        this.emails.remove(index);
        return true;
    }

    public boolean updateTelefone(int index, String rotulo, String valor){
        this.telefones.set(index, new Telefone(rotulo, valor));
        return true;
    }

    public boolean updateEmail(int index, String rotulo, String valor){
        this.emails.set(index, new Email(rotulo, valor));
        return true;
    }

    public String toString(){
        return String.format("nome: %s, sobrenome: %s, data de nascimento: %s, telefones: %s, emails: %s", this.nome, this.sobrenome, dataNasc.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")), formatArrayListToString(this.telefones), formatArrayListToString(this.emails));
    }

    private String formatArrayListToString(ArrayList<?> arrayList){
        StringBuilder sb = new StringBuilder();
        sb.append("(");
        for (int i = 0; i < arrayList.size(); i++) {
            sb.append(i);
            sb.append(" - ");
            sb.append(arrayList.get(i));
            if(i != arrayList.size() - 1){
                sb.append(", ");
            }
        }
        sb.append(")");
        return sb.toString();
    }



}
